language: go
go:
  - 1.11.x
matrix:
  include:
    - os: linux
      env: MAKE=make
    - os: osx
      env: MAKE=make
    - os: windows
      env: MAKE=mingw32-make
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
before_install:
  - "[[ $TRAVIS_OS_NAME != osx ]] || brew list bash || brew install bash"
  - "[[ $TRAVIS_OS_NAME != osx ]] || brew list coreutils || brew install coreutils"
install:
  - $MAKE depend
script:
  - $MAKE test
  - $MAKE build
