language: go
go:
  - 1.11.x
matrix:
  include:
    - os: linux
      env: MAKE=make
    - os: osx
      env: MAKE=make
    - os: windows
      env: MAKE=mingw32-make
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
install:
  - $MAKE depend
script:
  - gofmt -d *.go
  - $MAKE test
  - $MAKE build
